services:
  backend:
    build:
      context: ./IOT_challenge_BE
    container_name: iot-backend
    ports:
      - "3000:3000"
    env_file:
      - ./IOT_challenge_BE/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./IOT_challenge
    container_name: iot-frontend
    ports:
      - "8080:80"  # ⚠️ tránh trùng cổng 80 của host nếu bạn có Nginx
    depends_on:
      - backend
    restart: unless-stopped
  